name: Test Action

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: windows-latest
    strategy:
      matrix:
        version: ['4', '5', '6', '7']
        toolchain:
          - aarch64-elf
          - aarch64-linux-gnu
          - aarch64_be-elf
          - aarch64_be-linux-gnu
          - arm-eabi
          - arm-linux-gnueabi
          - arm-linux-gnueabihf
          - armeb-eabi
          - armeb-linux-gnueabi
          - armeb-linux-gnueabihf
          - armv8l-linux-gnueabihf

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install the GCC Linaro toolchain
        uses: ./
        with:
          version: ${{ matrix.version }}
          toolchain: ${{ matrix.toolchain }}
      
      - name: Verify the GCC cross compiler
        run: |
          ${{ matrix.toolchain }}-gcc --version

      - name: Run a sample build command
        shell: bash
        run: |
          # Creates a hello.c file
          echo '#include <stdio.h>' > hello.c
          echo 'int main() {' >> hello.c
          echo '    printf("Hello, ARM world!\\n");' >> hello.c
          echo '    return 0;' >> hello.c
          echo '}' >> hello.c

          # Conditional compilation command based on toolchain
          if [[ "${{ matrix.toolchain }}" == *"elf"* ]]; then
            COMPILER_COMMAND="${{ matrix.toolchain }}-gcc hello.c -o hello -specs=aem-ve.specs"
          else
            COMPILER_COMMAND="${{ matrix.toolchain }}-gcc hello.c -o hello"
          fi
          
          echo "Compiling with: $COMPILER_COMMAND"
          $COMPILER_COMMAND || exit 1  # Exit if compilation fails
